name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment info
        run: |
          uname -a
          ldd --version
          lsb_release -a
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --ignore-scripts=false

      - name: Build
        run: pnpm build

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
